[tool.isort]
profile = "black"
line_length = 88

[tool.black]
line-length = 88

[tool.mypy]
plugins = [
  "pydantic.mypy",
]
namespace_packages = true
explicit_package_bases = true

strict = true
warn_unreachable = false

disallow_incomplete_defs = false
disallow_untyped_defs = false
disallow_untyped_calls = false
no_implicit_reexport = false
warn_return_any = false
warn_unused_ignores = true

enable_error_code = [
  "redundant-expr",
  "truthy-bool",
  "ignore-without-code",
  "unused-awaitable",
  "type-arg",
  "redundant-cast",
  "comparison-overlap",
  "unreachable",
]

# disabled optional checks (false by default)
# explicitly excluded here.
disable_error_code = [
  "no-any-unimported",
]

# Error Formatting
show_column_numbers = true
show_error_context = true
show_error_codes = true
show_traceback = true
pretty = true
color_output = true
error_summary = true

[tool.pydantic-mypy]
init_forbid_extra = true
init_typed = true
warn_required_dynamic_aliases = true
